elegant_notes/elegant_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user_app.urls')),
    path('notes/', include('notes_app.urls')),
    path('', include('home_app.urls')),
]

elegant_notes/home_app/urls.py
from django.urls import path, include
from . import views

app_name = "home_app"
urlpatterns = [
    path('', views.main_page, name = 'main_page'),
]

elegant_notes/notes_app/urls.py
from django.urls import path, include
from . import views

app_name = "notes_app"
urlpatterns = [
    path('', views.home_view, name = 'home'),
    path('delete/<int:pk>', views.delete_view, name = 'delete'),
    path('create/', views.create_view, name = 'create'),
    path('update/<int:pk>', views.update_view, name = 'update')

]

elegant_notes/user_app/urls.py
from django.urls import path, include
from . import views

app_name = "user_app"
urlpatterns = [
    path('register/', views.register_page, name= 'register'),
    path('login/', views.login_page, name= 'login'),
    path('logout/', views.logout_page, name= 'logout'),
]

elegant_notes/home_app/models.py
from django.db import models

# Create your models here.

elegant_notes/notes_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Note(models.Model):
    title=models.CharField(max_length=45,null=False)
    description=models.TextField(null=False)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

elegant_notes/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

elegant_notes/notes_app/forms.py
from django import forms
from .models import Note



class NoteCreateForm(forms.ModelForm):
    class Meta:
        model=Note
        fields=['title','description']

class NoteUpdateForm(forms.ModelForm):
    class Meta:
        model=Note
        fields=['title','description']

elegant_notes/user_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

elegant_notes/home_app/views.py
from django.shortcuts import render

# Create your views here.
def main_page(request):
    context = {}
    return render(request, 'main_page.html')

elegant_notes/notes_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
# Create your views here.
from .models import Note
from .forms import NoteCreateForm,NoteUpdateForm
from django.contrib.auth.decorators import login_required

#view for home of a user. Unauthenticated users will be redirected
@login_required(login_url="/account/login/")
def home_view(request):
    notes = Note.objects.filter(author=request.user.id).order_by('updated_on')
    context = {'notes': notes}
    return render(request, 'home.html', context)

# delete_view, create_view and update_view receive request from AJAX section and status code and Json response is returned 
def delete_view(request,pk):
    if request.method != 'DELETE':
        return JsonResponse({'error': 'Invalid request method. Use DELETE.'}, status=400)

    try:
        note = Note.objects.get(id=pk)
    except Note.DoesNotExist:
        return JsonResponse({'error': 'Note not found'}, status=404)

    note.delete()
    return JsonResponse({'message': 'Note deleted successfully'}, status=200)


def create_view(request):
    form=NoteCreateForm()

    if request.method == "POST":
        form=NoteCreateForm(request.POST)

        if form.is_valid():
            note_obj=form.save(commit=False)
            note_obj.author=request.user
            note_obj.save()
            return JsonResponse({'message': 'Note created successfully'}, status=200)
    return JsonResponse({'message': 'Request method not allowed'}, status=405)

def update_view(request, pk):
    try:
        note = Note.objects.get(id=pk)
    except Note.DoesNotExist:
        return JsonResponse({'error': 'Note not found'}, status=404)
    form = NoteUpdateForm(instance=note)


    if request.method == "POST":
        form = NoteUpdateForm(request.POST)

    
        if form.is_valid():
            note.title = form.cleaned_data['title']
            note.description = form.cleaned_data['description']
            note.save()
            return JsonResponse({'message': 'Note updated successfully'}, status=200)
    return JsonResponse({'message': 'Request method not allowed'}, status=405)

elegant_notes/user_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def register_page(request):
    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data['username']
            messages.success(request, 'Account created successfully. Please Login.')
            return redirect('user_app:login')


    context = {'form': form}
    return render(request, 'register.html', context)

def login_page(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('notes_app:home')
        else:
            messages.info(request, 'Username OR Password is incorrect')

    context = {}
    return render(request, 'login.html', context)

def logout_page(request):
    logout(request)
    return redirect('home_app:main_page')

elegant_notes/home_app/templates/base.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Elegant Notes</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<style>
		body,
		html { 
			margin: 0;
			padding: 0;
			height: 100%;
			background: #5cdb95 !important;
		}

		.navbar-custom-color {
			background-color: #05386b;
		}

		.navbar-brand-font {
			font-family: Verdana, Geneva, Tahoma, sans-serif;
		}
		
		.logo-custom {
            color: #edf5e1;
        }

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #379683;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.input-group-text {
			background: #edf5e1 !important;
			color: #05385b !important;

        }

		.navbar{
            height: 54px;
        }


	</style>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark navbar-custom-color">
		<a class="navbar-brand navbar-brand-font" href=""><span style="color: #edf5e1"><i class="fas fa-sticky-note"></i></span><span style="color: #edf5e1"> Elegant Notes</span></span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
		  <ul class="navbar-nav">
			<li class="nav-item">
			  <a class="nav-link new-note-custom" href="/account/register/"><span class="input-group-text"><i class="fas fa-plus"></i><span style="padding-left: 0.5em; font-family: sans-serif, Verdana, Tahoma;">New Note</span></span></a>
			</li>
		  </ul>
		</div>
	  </nav>
    {% block content %}


    {% endblock %}



</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

elegant_notes/home_app/templates/main_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="container-fluid">
    <!-- Row for the two columns -->
    <div class="row">
      <!-- First column -->
      <div class="col-6" style="height: calc(100vh - 70px);">
        <div style="display: flex; align-items: center; justify-content: center; height: 100%; width: 100%;">
          <div style="text-align: center;">
            <h1 class="display-3">Your Notes.</h1>
            <h1 class="display-3">Organized.</h1>
            <h1 class="display-3">Elegantly.</h1>
            <br>
            <br>
            <br>
            <div class="d-flex justify-content-center align-items-center">
              <div class="d-flex">
                <a class="btn btn-primary btn-lg home-button" href="{% url 'user_app:register' %}" style="background-color: #05386b; margin-right: 4em; font-family: sans-serif, Verdana, Tahoma;">Sign up</a>
                <a class="btn btn-secondary btn-lg home-button" href="{% url 'user_app:login' %}" style="background-color: #05386b; margin-right: 1em; font-family: sans-serif, Verdana, Tahoma;">Log in</a>
              </div>
            </div>
          </div>
        </div>
        
      </div>
  
      <!-- Second column -->
      <div class="col-6 d-flex align-items-center justify-content-center" style="height: calc(100vh - 70px);">
        <img src="{% static 'notes.svg' %}" class="img-fluid">
      </div>
    </div>
  </div>
{% endblock %}

elegant_notes/user_app/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Elegant Notes Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #5cdb95 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #379683;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			cursor: pointer;
			width: 100%;
			background: #05386b !important;
			color: white !important;
		}




		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #05386b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{

			margin-top: 10px;
		}

        .ml-2{
            color: #013c77;
        }
		.navbar-custom-color{
			background-color: #05386b;
		}

		.navbar{
            height: 54px;
        }


	</style>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark navbar-custom-color">
		<a class="navbar-brand navbar-brand-font" href="/"><span style="color: #edf5e1"><i class="fas fa-sticky-note"></i></span><span style="color: #edf5e1"> Elegant Notes</span></span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  </nav>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Elegant Notes</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Log in">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
					{% if message.tags == "success" %}
                    	<p id="messages" class="alert alert-success" role="alert">{{message}}</p>
					{% endif %}
					{% if message.tags == "info" %}
					<p id="messages" class="alert alert-danger" role="alert">{{message}}</p>
					{% endif %}
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'user_app:register' %}" class="ml-2">Sign up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

elegant_notes/user_app/templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Elegant Notes Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #5cdb95 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #379683;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
            font-family: Verdana, Geneva, Tahoma;
		}
		.login_btn {
			width: 100%;
			background: #05386b !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #05386b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

        .ml-2{
            color: #013c77;
        }
		.navbar-custom-color{
			background-color: #05386b;
		}

		.navbar{
            height: 54px;
        }

	</style>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark navbar-custom-color">
		<a class="navbar-brand navbar-brand-font" href="/"><span style="color: #edf5e1"><i class="fas fa-sticky-note"></i></span><span style="color: #edf5e1"> Elegant Notes</span></span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  </nav>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Elegant Notes</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Create Account">
				   		</div>
					</form>
				</div>

                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'user_app:login' %}" class="ml-2">Log in</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>



